### ISSUE TITLE
Improve 'get' option for checkPermission

### ISSUE THREAD

**Issue by markcherbaka** [digitalbazaar/bedrock-permission#8]
When a function is sent in using the 'get' option, the get function is only executed under certain conditions.  If there isn't proper sanitation of the parameters being sent in, the get function may not execute as the user intended and may expose some security issues.

For example, consider the case when one tries to update a public key and sends in an actor and new key for the permission check (along with a get function that looks up the proper publicKey in the database) that don't match the owner in the database.  In this case, the new key will have valid owner and id fields, so the conditional (https://github.com/digitalbazaar/bedrock-permission/blob/c53e4bb9d9204ea90528c2fc9d58ef6a4dd1f1c5/lib/index.js#L545) evaluates to false and doesn't execute the 'get' function.  Therefore, the translate occurs using the owner of the key passed in, not the key in the database.  It's possible that an actor could update fields (such as the label field) that they are not authorized to update if the user of this API is not careful.

Several modifications are suggested:
1.) The if statement (https://github.com/digitalbazaar/bedrock-permission/blob/c53e4bb9d9204ea90528c2fc9d58ef6a4dd1f1c5/lib/index.js#L543) is difficult to follow.  A helper function (perhaps 'isSubset') to replace L546 would help readability, as would better commenting.
2.) A 'forceGet' or similar option could remove the conditionals to running the helper function while leaving the 'get' option as is for existing code.  This option can reduce confusion if a helper function is always expected to be run.

**Comment by dlongley** [comment]
Thinking about this further, since the current code path (skip using `options.get` sometimes) is just an optimization, we could actually just shut it off without needing people to adopt a flag to avoid it. We could either add a flag that would avoid it if possible (so the inverse of `forceGet`) or we could just say that if you're trying to optimize the use of `get`, then it's your responsibility to do so within your own custom `get` function. The only drawback to this approach is that existing higher-level APIs, such as the `updatePublicKey` one mentioned in the OP, provide no way for their caller to take advantage of that sort of optimization. It's only useful for the caller of the permission API itself.
